---

- name: Create partition 
  hosts: all
  vars:
    - default_user_password: Password1
  gather_facts: true
  tasks:
    - name: Create User task
      user:
        name: shahm
        state: present
        password: "{{ default_user_password | password_hash('sha512', 'A512') }}"
        shell: /bin/bash  
    - name: Create Partition 
      parted:
        device: /dev/nvme1n1
        number: 1
        state: present
    - name: Create file system
      filesystem:
        dev: /dev/nvme1n1p1
        fstype: xfs
        state: present
    - name: Mount /apps01
      mount:
        path: /apps01
        src: /dev/nvme1n1p1
        fstype: xfs
        state: mounted
