---

- name: Create New Users
  hosts: all
  vars:
    - default_user_password: Password1
  gather_facts: true
  tasks:
    - name: Create User task
      user:
        name: shahm
        state: present
        password: "{{ default_user_password | password_hash('sha512', 'A512') }}"
        shell: /bin/bash  



...
