---
- name: Playbook to copy file and uncompress
  hosts: all
  remote_user: ec2-user
  vars:
    - tomcat_home: "/apps01/wdtvs/apache/tomcat/wdtvs"
    - tomcat_instl_file: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.52/bin/apache-tomcat-9.0.52.zip"
  tasks:
  - name : Copy and Install Tomcat
    become: yes
    tags: tomcatinstall
    unarchive:
      src: "{{ item }}"
      dest: "{{ tomcat_home }}"
      mode: 0755
    with_items:
      - "{{ tomcat_instl_file }}"

- name: Playbook to copy Java file and uncompress
  hosts: all
  vars:
    - java_home: "/opt/jdk"
    - jdk_instl_file: "https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.12%2B7/OpenJDK11U-jdk_x64_linux_hotspot_11.0.12_7.tar.gz"

  tasks:
  - name : Copy and Install Java
    become: yes
    tags: javainstall
    unarchive:
      src: "{{ item }}"
      dest: "{{ java_home }}"
      mode: 0755
    with_items:
      - "{{ jdk_instl_file }}"


